# Generated by Django 3.1.5 on 2021-01-29 01:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('AdminThird', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='活动名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('end_time', models.DateTimeField(verbose_name='截止时间')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': '活动主体',
                'verbose_name_plural': '活动主体',
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ActivitySignUp.activity', verbose_name='活动')),
                ('admin_third', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminThird.adminthird', verbose_name='三级管理员')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='参与客户')),
            ],
            options={
                'verbose_name': '活动记录',
                'verbose_name_plural': '活动记录',
            },
        ),
    ]
