# Generated by Django 3.1.5 on 2021-02-02 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSecond', '0001_initial'),
        ('ActivitySignUp', '0003_auto_20210201_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='admin_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminSecond.adminsecond', verbose_name='二级管理员'),
        ),
    ]
