# Generated by Django 3.1.5 on 2021-02-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tag',
            field=models.CharField(default='无', max_length=100, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tag_type',
            field=models.CharField(default='secondary', max_length=20, verbose_name='标签类型'),
        ),
    ]
