# Generated by Django 3.1.5 on 2021-02-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20210202_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='card_num',
            field=models.CharField(default='', max_length=20, verbose_name='邮政卡卡号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='是否会员'),
        ),
    ]
