# Generated by Django 3.1.5 on 2021-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20210219_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='密码'),
        ),
    ]
