# Generated by Django 3.1.5 on 2021-02-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_auto_20210225_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.TextField(default='', verbose_name='备注'),
        ),
    ]
