# Generated by Django 3.1.7 on 2021-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_auto_20210812_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_catering_merchant',
            field=models.BooleanField(blank=True, help_text='是否为餐饮商户', null=True, verbose_name='是否为餐饮商户'),
        ),
    ]
