# Generated by Django 3.1.7 on 2021-10-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_customer_is_catering_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='integral',
            field=models.IntegerField(default=0, help_text='积分', verbose_name='积分'),
        ),
    ]
