# Generated by Django 3.1.7 on 2021-10-24 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_customer_integral'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegralGiveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(help_text='发放管理员姓名', max_length=32, verbose_name='发放管理员姓名')),
                ('give_num', models.IntegerField(help_text='发放数量', verbose_name='发放数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('customer', models.ForeignKey(help_text='客户', on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '积分发放记录',
                'verbose_name_plural': '积分发放记录',
            },
        ),
    ]
