# Generated by Django 3.1.7 on 2022-03-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_integralgivelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='96e79218965eb72c92a549dd5a330112', max_length=100, verbose_name='密码'),
        ),
    ]
