# Generated by Django 3.1.7 on 2021-08-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商品名', max_length=200, verbose_name='商品名')),
                ('remain_num', models.IntegerField(help_text='库存量', verbose_name='库存量')),
                ('description', models.TextField(help_text='介绍', verbose_name='介绍')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
