# Generated by Django 3.1.7 on 2021-08-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除'),
        ),
    ]
