# Generated by Django 3.1.7 on 2021-08-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_customer_comment'),
        ('Merchandise', '0002_merchandise_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveMerchandiseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_num', models.IntegerField(help_text='发放数量', verbose_name='发放数量')),
                ('give_time', models.DateTimeField(auto_now_add=True, help_text='发放时间', verbose_name='发放时间')),
                ('give_admin_name', models.CharField(help_text='管理员姓名', max_length=200, verbose_name='管理员姓名')),
                ('customer', models.ForeignKey(help_text='客户', on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='客户')),
                ('merchandise', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='Merchandise.merchandise', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品发放记录',
                'verbose_name_plural': '商品发放记录',
            },
        ),
    ]
