# Generated by Django 3.1.5 on 2021-02-04 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='镇名')),
            ],
            options={
                'verbose_name': '镇子',
                'verbose_name_plural': '镇子',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='村名')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Address.town', verbose_name='镇名')),
            ],
            options={
                'verbose_name': '村子',
                'verbose_name_plural': '村子',
            },
        ),
    ]
