# Generated by Django 3.1.5 on 2021-02-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='组名')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Address.village', verbose_name='村名')),
            ],
            options={
                'verbose_name': '组',
                'verbose_name_plural': '组',
            },
        ),
    ]
