# Generated by Django 3.1.5 on 2021-02-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0002_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='town',
            new_name='village',
        ),
    ]
