# Generated by Django 3.1.7 on 2021-10-06 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RequestAction', '0002_auto_20211006_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestactionlog',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
