# Generated by Django 3.1.7 on 2021-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestAction', '0003_requestactionlog_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestactionlog',
            name='remark',
            field=models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注'),
        ),
    ]
